# This workflow deploy system tools to development environment

name: Deployment of system tools modules to development env

on:
  push:
    branches: [ "sys_conf", "sys_log", "sys_shd" ]
  
  pull_request_review:
    # types: [edited]
    review:
      state: [approved]
    pull_request:
      base:
        ref: [ "sys_conf", "sys_log", "sys_shd" ] 


jobs:
  
  build-package-on-push:
    if: ${{ github.event_name == 'push'}}
    name: Build package ${{ github.ref_name }}
    uses: ./.github/workflows/build_python_package.yml
    with:
      module_name: ${{ github.ref_name }}
  
  build-package-on-pull-request:
    if: ${{ github.event_name == 'pull_request_review' }}
    name: Build package  ${{ github.event.pull_request.head.ref }}
    uses: ./.github/workflows/build_python_package.yml
    with:
      module_name: ${{ github.event.pull_request.head.ref }}
    
  publish-package:
    
    name: Publish package ${{ github.event.pull_request.head.ref }} to PyPi
    if: ${{ github.event_name == 'pull_request_review' }}
    needs: build-package-on-pull-request
    runs-on: ubuntu-latest
    environment: development
    permissions:
      id-token: write
      # strategy:
        #   fail-fast: false
        #   matrix:
          #     # python-version: ["3.7", "3.9", "3.11"]
          #     python-version: ["3.11"]

    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name:  ${{ github.event.pull_request.head.ref }}
          path: ${{ github.event.pull_request.head.ref }}/dist/

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@f8c70e705ffc13c3b4d1221169b84f12a75d6ca8
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: ${{ github.event.pull_request.head.ref }}/dist/
